apiVersion: batch/v1beta1
kind: CronJob
metadata:
 name: cronjob-everyminute
spec:
 schedule: "*/1 * * * *"
 jobTemplate:
  spec:
   template:
     spec:
      containers:
       - name: busybox
         image: busybox
         command: ["date"]
      restartPolicy: OnFailure 

