apiVersion: v1
kind: Secret
metadata:
 name: my-secret
data:
 my-username: YWRtaW4=
 my-password: cGFzd3dvcmQ=
---
apiVersion: v1
kind: Pod
metadata:
 name: pod-with-secert-env-var
spec:
 containers:
  - name: nginx
    image: nginx
    env:
    - name: MY_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: my-username
    - name: MY_PASSWORD
      valueFrom:
        secretKeyRef:
           name:  my-secret
           key: my-password
  
