apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv02
 namespace: elk-namespace
spec:
 capacity:
  storage: 2Gi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
 persistentVolumeReclaimPolicy: Recycle
 storageClassName: rook-block
 hostPath:
  path: "/data"
