apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-data
  namespace: elk-namespace
  labels:
    app: es-node
    env: dev
    nodetype: elasticsearch-node
spec:
  serviceName: es-discovery
  replicas: 2 # scale when desired
  selector:
    matchLabels:
      app: es-node
  template:
    metadata:
      labels:
        app: es-node
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-data
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: discovery.zen.ping.unicast.hosts
          #value: "elasticsearch-sticsearch-data-0.elasticsearch-discovery.elk-namespace.svc.cluster.local,elasticsearch-sticsearch-data-1.elasticsearch-discovery.elk-namespace.svc.cluster.local"
          value: "es-discovery.elk-namespace.svc.cluster.local"
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: cluster.name
          value: elasticsearch
        - name: node.data
          value: "true"
        - name: node.master
          value: "false"
        - name: node.ingest
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: 0.25
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        volumeMounts:
        - name: elasticsearch-data-storage
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: elasticsearch-data-storage
    spec:
      storageClassName: rook-block
      accessModes: [ ReadWriteOnce ]
      resources:
        requests:
          storage: 2Gi # small for dev / testing
