apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-master
  namespace: elk-namespace
  labels:
    app: es-node
    env: dev
    nodetype: elasticsearch-master
spec:
  replicas: 2 # scale as desired (see NUMBER_OF_MASTERS below)
  selector:
    matchLabels:
      app: es-node
      nodetype: elasticsearch-master
      env: dev
  template:
    metadata:
      labels:
        app: es-node
        env: dev
        nodetype: elasticsearch-master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch-master
        image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
        imagePullPolicy: Always
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.zen.ping.unicast.hosts
          value: "es-discovery.elk-namespace.svc.cluster.local"
        - name: cluster.name
          value: elasticsearch
        - name: discovery.zen.minimum_master_nodes
          value: "2"
        - name: node.master
          value: "true"
        - name: node.ingest
          value: "false"
        - name:  node.data
          value: "false"
        - name: HTTP_ENABLE
          value: "false"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        - name: PROCESSORS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        resources:
          limits:
            cpu: 0.25
        ports:
        - containerPort: 9300
          name: transport
        - containerPort: 9200
          name: http
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
      - emptyDir:
          medium: ""
        name: "storage"
