---
- name: restart kubelet
  systemd:
    name: kubelet
    daemon_reload: yes
    state: restarted
    enabled: yes

- name: restart kube-proxy
  systemd:
    daemon_reload: yes
    enabled: yes
    name: kube-proxy
    state: restarted
