---
- name: Generate Admin private key
  openssl_privatekey:
    path: '{{ user_accounts_pki_dir }}/admin.key'

- name: Generate Admin CSR
  openssl_csr:
    path: '{{ user_accounts_pki_dir }}/admin.csr'
    privatekey_path: '{{ user_accounts_pki_dir }}/admin.key'
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    extended_key_usage:
      - serverAuth
      - clientAuth
    common_name: kubernetes-admin
    organization_name: "system:masters"

- name: Generate Admin certificate
  openssl_certificate:
    path: '{{ user_accounts_pki_dir }}/admin.crt'
    csr_path: '{{ user_accounts_pki_dir }}/admin.csr'
    ownca_path: '{{ k8s_pki_dir }}/k8s-ca.crt'
    ownca_privatekey_path: '{{ k8s_pki_dir }}/k8s-ca.key'
    provider: ownca
