---
- name: Generate controller manager private key
  openssl_privatekey:
    path: '{{ k8s_pki_dir }}/kube-controller-manager.key'

- name: Generate controller manager csr
  openssl_csr:
    path: '{{ k8s_pki_dir }}/kube-controller-manager.csr'
    privatekey_path: '{{ k8s_pki_dir }}/kube-controller-manager.key'
    common_name: 'system:kube-controller-manager'
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    extended_key_usage: clientAuth
    organization_name: 'system:kube-controller-manager'

- name: Generate controller manager certificate
  openssl_certificate:
    path: '{{ k8s_pki_dir }}/kube-controller-manager.crt'
    csr_path: '{{ k8s_pki_dir }}/kube-controller-manager.csr'
    ownca_path: '{{ k8s_pki_dir }}/k8s-ca.crt'
    ownca_privatekey_path: '{{ k8s_pki_dir }}/k8s-ca.key'
    provider: ownca

- name: Generate service account private key
  openssl_privatekey:
    path: '{{ k8s_pki_dir }}/service-account.key'

- name: Generate service account csr
  openssl_csr:
    path: '{{ k8s_pki_dir }}/service-account.csr'
    privatekey_path: '{{ k8s_pki_dir }}/service-account.key'
    common_name: 'service-account'
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    extended_key_usage: clientAuth
    extended_key_usage_critical: true

- name: Generare service account certificate
  openssl_certificate:
    path: '{{ k8s_pki_dir }}/service-account.crt'
    csr_path: '{{ k8s_pki_dir }}/service-account.csr'
    ownca_path: '{{ k8s_pki_dir }}/k8s-ca.crt'
    ownca_privatekey_path: '{{ k8s_pki_dir }}/k8s-ca.key'
    provider: ownca
