---
- name: Generate kubelet servers private keys
  openssl_privatekey:
    path: '{{ k8s_pki_dir }}/{{ item }}.key'
  loop: "{{ groups['node'] }}"

- name: Generate kubelet servers csrs
  openssl_csr:
    path: "{{ k8s_pki_dir }}/{{ item }}.csr"
    privatekey_path: "{{ k8s_pki_dir }}/{{ item }}.key"
    common_name: "system:node:{{ item }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    extended_key_usage:
      - clientAuth
      - serverAuth
    extended_key_usage_critical: true
    organization_name: 'system:nodes'
    subject_alt_name:
      - DNS:{{ item }}
      - IP:{{ hostvars[item]['ansible_host'] }}
      - IP:127.0.0.1
  loop: "{{ groups['node'] }}"

- name: Generate kubelet servers certificates
  openssl_certificate:
    path: '{{ k8s_pki_dir }}/{{ item }}.crt'
    csr_path: '{{ k8s_pki_dir }}/{{ item }}.csr'
    ownca_path: '{{ k8s_pki_dir }}/k8s-ca.crt'
    ownca_privatekey_path: '{{ k8s_pki_dir }}/k8s-ca.key'
    provider: ownca
  loop: "{{ groups['node'] }}"

- name: Generate kubelet clients private keys
  openssl_privatekey:
    path: '{{ k8s_pki_dir }}/{{ item }}-client.key'
  loop: "{{ groups['node'] }}"

- name: Generate kubelet clients csrs
  openssl_csr:
    path: "{{ k8s_pki_dir }}/{{ item }}-client.csr"
    privatekey_path: "{{ k8s_pki_dir }}/{{ item }}-client.key"
    common_name: "system:node:{{ item }}"
    key_usage:
      - digitalSignature
      - keyEncipherment
    key_usage_critical: true
    extended_key_usage: clientAuth
    extended_key_usage_critical: true
    organization_name: 'system:nodes'
  loop: "{{ groups['node'] }}"

- name: Generate kubelet clients certificates
  openssl_certificate:
    path: '{{ k8s_pki_dir }}/{{ item }}-client.crt'
    csr_path: '{{ k8s_pki_dir }}/{{ item }}-client.csr'
    ownca_path: '{{ k8s_pki_dir }}/k8s-ca.crt'
    ownca_privatekey_path: '{{ k8s_pki_dir }}/k8s-ca.key'
    provider: ownca
  loop: "{{ groups['node'] }}"
