apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: nginx-ss
 labels:
  app: nginx-ss
spec:
 template: 
   metadata:
    labels:
     app: nginx-ss-pod
   spec:
    terminationGracePeriodSeconds: 10
    containers:
     - name: nginx-container
       image: k8s.gcr.io/nginx-slim:0.8
       ports:
        - name: http
          containerPort: 80
          protocol: TCP
       volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
 volumeClaimTemplates:
  - metadata:
     name: www
    spec:
     accessModes: ["ReadWriteOnce"]
     storageClassName: "my-storage-class"
     resources:
      requests:
       storage: 1Gi
    
