kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: istio
networking:
  ipFamily: ipv4
  apiServerAddress: 0.0.0.0
  apiServerPort: 6443
  podSubnet: "192.168.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: true
  kubeProxyMode: "ipvs"
nodes:
  - role: control-plane
    image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
             advertise-address: "192.168.5.210"
             bind-address: "0.0.0.0"

             enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
          certSANs:
            - "192.168.5.210"
            - "127.0.0.1"
            - "10.96.0.1"
            - "172.18.0.2"
            - "0.0.0.0"
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
             node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP                
    extraMounts:
    - hostPath: /home/
      containerPath: /host_folder
  - role: worker
    image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
    - hostPath: /home/
      containerPath: /host_folder
  - role: worker
    image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
    - hostPath: /home/
      containerPath: /host_folder
  - role: worker
    image: kindest/node:v1.31.2@sha256:18fbefc20a7113353c7b75b5c869d7145a6abd6269154825872dc59c1329912e
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true" 
    extraMounts:
    - hostPath: /home/
      containerPath: /host_folder