kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: istio
networking:
  ipFamily: ipv4
  apiServerAddress: 0.0.0.0
  apiServerPort: 6443
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: true
  kubeProxyMode: none
#  kubeProxyMode: "ipvs"
nodes:
  - role: control-plane
    image: kindest/node:v1.27.16@sha256:2d21a61643eafc439905e18705b8186f3296384750a835ad7a005dceb9546d20
    kubeadmConfigPatches:
      - |
        kind: ClusterConfiguration
        apiServer:
          extraArgs:
             bind-address: "0.0.0.0"

             enable-admission-plugins: NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook
          certSANs:
            - "192.168.4.40"
            - "127.0.0.1"
            - "10.96.0.1"
            - "172.18.0.2"
            - "0.0.0.0"
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
             node-labels: "ingress-ready=true"
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: 127.0.0.1
      - containerPort: 443
        hostPort: 443
        protocol: TCP  
        listenAddress: 127.0.0.1              
    extraMounts:
    - hostPath: /home/
      containerPath: /host_folder
  - role: worker
    image: kindest/node:v1.27.16@sha256:2d21a61643eafc439905e18705b8186f3296384750a835ad7a005dceb9546d20
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
    - hostPath: /home/
      containerPath: /host_folder
  - role: worker
    image: kindest/node:v1.27.16@sha256:2d21a61643eafc439905e18705b8186f3296384750a835ad7a005dceb9546d20
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraMounts:
    - hostPath: /home/
      containerPath: /host_folder
  - role: worker
    image: kindest/node:v1.27.16@sha256:2d21a61643eafc439905e18705b8186f3296384750a835ad7a005dceb9546d20
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true" 
    extraMounts:
    - hostPath: /home/
      containerPath: /host_folder