apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-cache
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web-cache
    spec:
      containers:
      - name: redis-server
        image: redis:3.2-alpine
