apiVersion: apps/v1
kind: DaemonSet
metadata:
 name: my-daemonset02
 labels:
  app: logging-process-ds-02
spec:
 selector:
  matchLabels:
    app: logging-process-02
 template:
  metadata:
   labels:
    app: logging-process-02
  spec:
   tolerations:
    - key: node-role.kubernetes.io/master
      value: NoSchedule
   containers:
    - name: my-logging-container
      image: k8s.gcr.io/fluentd-elasticsearch:1.20
      resources:
       limits:
        memory: 200Mi
       requests:
        cpu: 100m
      volumeMounts:
       - name: varlog
         mountPath: /var/log
       - name: varlogcontainer
         mountPath: /var/lib/docker/containers
         readOnly: true
   terminationGracePeriodSeconds: 30
   volumes:
    - name: varlog
      hostPath:
       path: /var/log
    - name : varlogcontainer
      hostPath:
       path: /var/lib/docker/containers      

