apiVersion: v1
kind: PersistentVolume
metadata:
 name: redis-pv
 namespace: redis
spec:
 capacity:
  storage: 5Gi
 storageClassName: redis
 accessModes:
  - ReadWriteOnce
  - ReadWriteMany
 hostPath:
  path: "/redis/data"

