apiVersion: v1
kind: LimitRange
metadata:
 name: my-limit-range
 namespace: default-mem-example
spec:
 limits:
  - default:
     memory: 512Mi
    defaultRequest:
      memory: 256Mi
    type: Container
