apiVersion: v1
kind: LimitRange
metadata:
 name: min-max-memcpu-limitrange
 namespace: min-max-memcpu
spec:
 limits:
 - max:
     memory: 512Mi
     cpu: 1
   min:
     memory: 256Mi
     cpu: 0.5
   type: Container
