---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: canal
spec:
  privileged: true
  hostNetwork: true
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  fsGroup:
    rule: RunAsAny
  volumes:
    - '*'

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: canal-psp
  namespace: kube-system
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - canal

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: canal-psp
  namespace: kube-system
roleRef:
  kind: Role
  name: canal-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: canal
    namespace: kube-system
