apiVersion: v1
kind: Pod
metadata:
 name: pod-liveness-probe
spec:
 containers:
  - name : nginx-c
    image: nginx
    livenessProbe:
     httpGet:
      path: /
      port: 80
     initialDelaySeconds: 30
     timeoutSeconds: 1
    ports:
     - containerPort: 80
