apiVersion: v1
kind: Pod
metadata:
 name: pod-readinessprobe-http
spec:
 containers:
  - name : nginx
    image: nginx
    readinessProbe:
     httpGet:
      port: 80
      path: /
     initialDelaySeconds: 30
     timeoutSeconds: 2
     periodSeconds: 5
     successThreshold: 2
     failureThreshold: 2
