kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: jEf8k9/TEWmhnHNCqzizcAkZRfHQISYQ9VsoBZvpI58=
      - identity: {}
