apiVersion: batch/v1beta1
kind: CronJob
metadata:
 name: my-cronjob-01
spec:
 schedule: " */1 * * * *"
 jobTemplate:
  spec:
   template:
    spec:
      containers:
       - name: busybox
         image: busybox
         args:
           - /bin/sh
           - -c
           - date; echo from container
      restartPolicy: OnFailure  
