apiVersion: v1
kind: Pod
metadata:
 name: pod-configmap-env
spec:
 containers:
  - name: busybox
    image: busybox
    command: ["/bin/sh" ,"-c" ,"env"]
    envFrom:
     - configMapRef:
        name: special-config
 restartPolicy: Never
