---
- name: Install nginx
  apt:
    name: nginx
    state: latest
    update_cache: yes

- name: Configure nginx
  blockinfile:
    path: /etc/nginx/nginx.conf
    block: |
      stream {
          upstream apiserver {
          {% for host in groups['master'] %}
            server {{ hostvars[host]['ansible_host'] }}:6443;
          {% endfor %}
          }

          upstream etcd {
          {% for host in groups['etcd'] %}
            server {{ hostvars[host]['ansible_host'] }}:2379;
          {% endfor %}
          }

          server {
                listen 6443;
                proxy_pass apiserver;
          }

          server {
                listen 2379;
                proxy_pass etcd;
          }
      }
  notify:
    - reload nginx
