apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv-spinnaker
 namespace: spinnaker
spec:
 capacity:
  storage: 10Gi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
 persistentVolumeReclaimPolicy: Recycle
 storageClassName: standard
 hostPath:
  path: "/spinnaker"
