apiVersion: v1
kind: Pod
metadata:
 name: pod02-for-pvc
spec:
 volumes:
  - name: pod02-vol
    persistentVolumeClaim:
      claimName: pvc-for-pv01
 containers:
  - name: nginx
    image: nginx
    volumeMounts:
     - name: pod02-vol
       mountPath: "/usr/share"
     
