apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv02
spec:
 capacity:
  storage: 1Gi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
  - ReadWriteMany
 persistentVolumeReclaimPolicy: Recycle
 storageClassName: slow
 hostPath:
  path: "/mnt"
