apiVersion: v1
kind: PersistentVolume
metadata:
 name: pv01
spec:
 capacity:
  storage: 2Gi
 volumeMode: Filesystem
 accessModes:
  - ReadWriteOnce
 persistentVolumeReclaimPolicy: Recycle
 storageClassName: slow
 hostPath:
  path: "/mnt"
