apiVersion: v1
kind: Pod
metadata:
 name: jump
spec:
 containers:
 - image: mohamedabdoun/linux
   name: jump
   tty: true
   stdin: true
   ports:
   - containerPort: 8080
     name: myhttpport
     protocol: TCP

