apiVersion: v1
kind: Pod
metadata:
 name: mulitple-containers-pod
spec:
 containers:
 - image: gcr.io/kuar-demo/kuard-amd64:1
   name: webserver
   tty: true
   ports:
   - containerPort: 8080
     name: http
     protocol: TCP
   - containerPort: 22
     name: ssh
     protocol: TCP
 - image: ubuntu
   name: ubuntu
   ports: 
    - containerPort: 22
      name: ssh
      protocol: TCP
 
     
