apiVersion: v1
kind: Pod
metadata:
 name: pod-resource-mgmt
spec:
 containers:
  - image: nginx:1.9
    name: nginx
    resources:
     requests:
      cpu: "500m"
      memory: "128Mi"
    ports:
     - containerPort: 8089
       name: httpport
       protocol: TCP
