apiVersion: v1
kind: Pod
metadata:
 name: pod-multi-volumes
spec:
 volumes:
  - name: "vol1"
    hostPath:
     path: "/k8s/volumes/vol1"
  - name: "vol2"
    hostPath:
     path: "/k8s/volumes/vol2"
  - name: "vol3"
    emptyDir: {}
 containers:
 - image: nginx
   name: nginx
   tty: true
   volumeMounts:
    - mountPath: "/vol1"
      name: "vol1"
    - mountPath: "/vol2"
      name: "vol2"
    - mountPath: "vol3"
      name: "vol3"
   ports:
   - containerPort: 8080
     name: http
     protocol: TCP
