apiVersion: v1
kind: Pod
metadata:
 name: pod-max-limit
spec:
 containers:
 - image: mohamedabdoun/linux
   name: ubuntu
   tty: true
   resources:
    requests:
     cpu: "500m"
     memory: "128Mi"
    limits:
     cpu: "700m"
     memory: "256Mi"
   ports:
   - containerPort: 22
     name: tcp
     protocol: TCP
    
