apiVersion: v1
kind: Pod
metadata:
 name: ubuntu
spec:
 containers:
 - image: ubuntu
   name: ubuntu
   tty: true
   stdin: true
   ports:
   - containerPort: 8080
     name: myhttpport
     protocol: TCP

