apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: myfirstreplicaset
spec:
 replicas: 2
 selector:
  matchLabels:
   app: webapp
 template:
  metadata:
   labels:
     app: webapp
     version: v11
  spec:
   containers:
    - name: frontendpod
      image: nginx
