apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: mysecondreplicaset
spec:
 replicas: 2
 selector:
  matchLabels:
   app: webapp2
  matchExpressions:
   - {key: version, operator: In , values: [v11]}
 template:
  metadata:
   labels:
     app: webapp2
     version: v11
  spec:
   containers:
    - name: frontendpod
      image: nginx
      volumeMounts:
       - name: sharedvol
         mountPath: "/mysharedvol"       
      ports:
      - name: http
        containerPort: 8080
        protocol: TCP
    - name: db-pod
      image: mysql
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: example
      resources:
       requests:
        memory: 100Mi 
   volumes:
    - name: sharedvol
      emptyDir: {}
