# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|

  config.vm.box = "generic/ubuntu1604"

  config.vm.define "k8smaster" do |kube|
    kube.vm.hostname = "k8smaster"
    #config.vm.provision "file", source: "/Users/mohamed/cloud_development/k8s/vagrant-kube-cluster/hosts_vmware", destination: "/etc/hosts"
    #config.vm.provision "file", source: "/Users/mohamed/cloud_development/k8s/vagrant-kube-cluster/kubernetes.list", destination: "/etc/apt/sources.list.d/kubernetes.list"
    kube.vm.synced_folder ".", "/vagrant"
    kube.vm.network "private_network", ip: "172.16.25.100"
   config.vm.provider "vmware_desktop" do |vmware|   
      vmware.allowlist_verified = true
      vmware.gui = true 
   end
    kube.vm.provision "shell", inline: $script
  end
 
config.vm.define "kube01" do |kube|
   kube.vm.hostname = "kube01"
   kube.vm.synced_folder ".", "/vagrant"
   kube.vm.network "private_network", ip: "172.16.25.101"
    config.vm.provider "vmware_desktop" do |vmware|   
     vmware.allowlist_verified = true
     vmware.gui = true  
  end
   kube.vm.provision "shell", inline: $script
 end

config.vm.define "kube02" do |kube|
   kube.vm.hostname = "kube02"
   kube.vm.synced_folder ".", "/vagrant"
   kube.vm.network "private_network", ip: "172.16.25.102"
   config.vm.provider "vmware_desktop" do |vmware|   
     vmware.allowlist_verified = true
     vmware.gui = true   
   end
   kube.vm.provision "shell", inline: $script
 end


$script = <<SCRIPT
echo I am provisioning...
#echo "r00tme" | passwd  root
sudo cp /vagrant/hosts_vmware /etc/hosts
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo cp /vagrant/kubernetes.list /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update 
sudo apt-get install  docker.io kubelet=1.19.14-00 kubeadm=1.19.14-00 kubectl=1.19.14-00 kubernetes-cni=0.8.7-00 -y
sudo rm -rf /var/lib/kubelet/*
echo I am turning off swap...
sudo swapoff -a
echo I am joining NFS...
sudo apt-get install nfs-common -y

SCRIPT

end
