# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"

  # Define the master node
  config.vm.define "k8s-master" do |kube|
    kube.vm.hostname = "k8s-master"
    kube.vm.synced_folder ".", "/vagrant"
    
    # Public network on the same WiFi network as the host
    kube.vm.network "public_network", ip: "192.168.4.100", bridge: "wlo1"

    # Configure resources
    kube.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--memory", "4048"]
      vb.customize ["modifyvm", :id, "--cpus", "2"]
    end
    
    # Provisioning script
    kube.vm.provision "shell", inline: $script
  end
#
#  # Define the first worker node
#  config.vm.define "kube-01" do |kube|
#    kube.vm.hostname = "kube-01"
#    kube.vm.synced_folder ".", "/vagrant"
#    
#    # Public network on the same WiFi network as the host
#    kube.vm.network "public_network", ip: "192.168.4.11", bridge: "wlo1"
#
#    # Configure resources
#    kube.vm.provider :virtualbox do |vb|
#      vb.customize ["modifyvm", :id, "--memory", "2048"]
#      vb.customize ["modifyvm", :id, "--cpus", "1"]
#    end
#
#    # Provisioning script
#    kube.vm.provision "shell", inline: $worker_script
#  end
#
#  # Define the second worker node
#  config.vm.define "kube-02" do |kube|
#    kube.vm.hostname = "kube-02"
#    kube.vm.synced_folder ".", "/vagrant"
#    
#    # Public network on the same WiFi network as the host
#    kube.vm.network "public_network", ip: "192.168.4.12", bridge: "wlo1"
#
#    # Configure resources
#    kube.vm.provider :virtualbox do |vb|
#      vb.customize ["modifyvm", :id, "--memory", "2048"]
#      vb.customize ["modifyvm", :id, "--cpus", "1"]
#    end
#
#    # Provisioning script
#    kube.vm.provision "shell", inline: $worker_script
#  end
#
#
$worker_script = <<SCRIPT
echo I am provisioning...
echo setting ssh key and configs
mkdir -p /home/vagrant/.ssh
chmod 700 /home/vagrant/.ssh
cat /vagrant/ssh/id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
sudo mkdir -p /root/.ssh && chmod 700 -R /root/.ssh && touch /root/.ssh/authorized_keys
sudo cat /vagrant/ssh/id_rsa.pub > /root/.ssh/authorized_keys
chmod -R 600 /home/vagrant/.ssh/authorized_keys
echo 'StrictHostKeyChecking no' >> /home/vagrant/.ssh/config
echo 'UserKnownHostsFile /dev/null' >> /home/vagrant/.ssh/config
 chmod -R 600 /home/vagrant/.ssh/config
 sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/g' /etc/ssh/sshd_config
sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config
sed -i 's/#PubkeyAuthentication yes/PubkeyAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart ssh
echo "####Setting root passowrd"
echo -e -n "r00tr00t\nr00tr00t" | sudo passwd root

sudo cp /vagrant/hosts_vmware /etc/hosts
echo I am turning off swap...
sudo echo "vm.swappiness=10" >> /etc/sysctl.conf
sudo sysctl --system
sudo swapoff -a
echo copying install_worker.sh
sudo cp /vagrant/install_worker.sh  /home/vagrant/install_worker.sh
sudo chmod 600 /home/vagrant/install_worker.sh
#sudo sh /home/vagrant/install_worker.sh
echo I am joining NFS...
sudo apt-get install nfs-common -y
echo $(id)
eval "sudo $(ssh -i /home/vagrant/.ssh/id_rsa -o StrictHostKeyChecking=no k8smaster 'kubeadm token create --print-join-command --ttl 0')"
SCRIPT

$script = <<SCRIPT
echo I am provisioning...
echo "r00tme" | passwd  root
sudo cp /vagrant/hosts_vmware /etc/hosts
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
sudo cp /vagrant/kubernetes.list /etc/apt/sources.list.d/kubernetes.list
sudo apt-get update 
sudo apt-get install  docker.io kubelet=1.19.14-00 kubeadm=1.19.14-00 kubectl=1.19.14-00 kubernetes-cni=0.8.7-00 -y
sudo rm -rf /var/lib/kubelet/*
echo I am turning off swap...
sudo echo "vm.swappiness=10" >> /etc/sysctl.conf
sudo sysctl --system
sudo swapoff -a
echo I am joining NFS...
sudo apt-get install nfs-common -y

echo copying install_master.sh
sudo cp /vagrant/install_master.sh  /home/vagrant/install_master.sh
sudo chmod 600 /home/vagrant/install_master.sh
sudo chown vargant:vagrant /home/vagrant/install_master.sh
sudo bash /home/vagrant/install_master.sh

SCRIPT


end
